package net.empire.ewmedieval.datagen;

import net.empire.ewmedieval.block.ModBlocks;
import net.empire.ewmedieval.util.ModTags;
import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricTagProvider;
import net.minecraft.block.Block;
import net.minecraft.block.Blocks;
import net.minecraft.registry.RegistryKeys;
import net.minecraft.registry.RegistryWrapper;
import net.minecraft.registry.tag.BlockTags;
import net.minecraft.registry.tag.TagKey;
import net.minecraft.util.Identifier;

import java.util.concurrent.CompletableFuture;

public class ModBlockTagProvider extends FabricTagProvider.BlockTagProvider {
    public ModBlockTagProvider(FabricDataOutput output, CompletableFuture<RegistryWrapper.WrapperLookup> registriesFuture) {
        super(output, registriesFuture);
    }

    public static final TagKey<Block> NEEDS_BRONZE_TOOL =
            TagKey.of(RegistryKeys.BLOCK, new Identifier("ewmedieval", "needs_bronze_tool"));

    @Override
    protected void configure(RegistryWrapper.WrapperLookup arg) {
       getOrCreateTagBuilder(BlockTags.PICKAXE_MINEABLE)
               .add(ModBlocks.RAW_TIN_BLOCK)
               .add(ModBlocks.TIN_BLOCK)
               .add(ModBlocks.TIN_ORE)
               .add(ModBlocks.DEEPSLATE_TIN_ORE)
               .add(ModBlocks.RAW_SILVER_BLOCK)
               .add(ModBlocks.SILVER_BLOCK)
               .add(ModBlocks.CUT_SILVER)
               .add(ModBlocks.DEEPSLATE_SILVER_ORE)
               .add(ModBlocks.KHAZAD_STEEL_BLOCK)
               .add(ModBlocks.EDHEL_STEEL_BLOCK)
               .add(ModBlocks.BURZUM_STEEL_BLOCK)
               .add(ModBlocks.CRUDE_BLOCK)
               .add(ModBlocks.RAW_LEAD_BLOCK)
               .add(ModBlocks.LEAD_BLOCK)
               .add(ModBlocks.CUT_LEAD)
               .add(ModBlocks.DEEPSLATE_LEAD_ORE)
               .add(ModBlocks.RAW_MITHRIL_BLOCK)
               .add(ModBlocks.MITHRIL_BLOCK)
               .add(ModBlocks.SLATE)
               .add(ModBlocks.SLATE_COPPER_ORE)
               .add(ModBlocks.SLATE_COAL_ORE)
               .add(ModBlocks.SLATE_BRICKS)
               .add(ModBlocks.SLATE_TIN_ORE)
               .add(ModBlocks.POLISHED_SLATE)
               .add(ModBlocks.COBBLED_SLATE)
               .add(ModBlocks.SLATE_WALL)
               .add(ModBlocks.SLATE_SLAB)
               .add(ModBlocks.SLATE_TRAPDOOR)
               .add(ModBlocks.SLATE_STAIRS)
               .add(ModBlocks.SLATE_BUTTON)
               .add(ModBlocks.SLATE_PRESSURE_PLATE)
               .add(ModBlocks.POLISHED_SLATE_SLAB)
               .add(ModBlocks.POLISHED_SLATE_STAIRS)
               .add(ModBlocks.POLISHED_SLATE_WALL)
               .add(ModBlocks.SLATE_BRICKS_WALL)
               .add(ModBlocks.SLATE_BRICKS_SLAB)
               .add(ModBlocks.SLATE_BRICKS_STAIRS)
               .add(ModBlocks.COBBLED_SLATE_WALL)
               .add(ModBlocks.COBBLED_SLATE_SLAB)
               .add(ModBlocks.COBBLED_SLATE_STAIRS)

               .add(ModBlocks.OLD_DEEPSLATE)
               .add(ModBlocks.OLD_DEEPSLATE_SLAB)
               .add(ModBlocks.OLD_DEEPSLATE_STAIRS)
               .add(ModBlocks.OLD_DEEPSLATE_WALL)

               .add(ModBlocks.SMOOTH_DEEPSLATE)
               .add(ModBlocks.SMOOTH_DEEPSLATE_SLAB)
               .add(ModBlocks.SMOOTH_DEEPSLATE_STAIRS)
               .add(ModBlocks.SMOOTH_DEEPSLATE_WALL)

               .add(ModBlocks.MOSSY_SMOOTH_DEEPSLATE)
               .add(ModBlocks.MOSSY_SMOOTH_DEEPSLATE_SLAB)
               .add(ModBlocks.MOSSY_SMOOTH_DEEPSLATE_STAIRS)
               .add(ModBlocks.MOSSY_SMOOTH_DEEPSLATE_WALL)

               .add(ModBlocks.CRACKED_SMOOTH_DEEPSLATE)
               .add(ModBlocks.CRACKED_SMOOTH_DEEPSLATE_SLAB)
               .add(ModBlocks.CRACKED_SMOOTH_DEEPSLATE_STAIRS)
               .add(ModBlocks.CRACKED_SMOOTH_DEEPSLATE_WALL)

               .add(ModBlocks.MOSSY_COBBLED_DEEPSLATE)
               .add(ModBlocks.MOSSY_COBBLED_DEEPSLATE_SLAB)
               .add(ModBlocks.MOSSY_COBBLED_DEEPSLATE_STAIRS)
               .add(ModBlocks.MOSSY_COBBLED_DEEPSLATE_WALL)

               .add(ModBlocks.DEEPSLATE_PILLAR)
               .add(ModBlocks.MOSSY_DEEPSLATE_PILLAR)
               .add(ModBlocks.CRACKED_DEEPSLATE_PILLAR)

               .add(ModBlocks.MOSSY_DEEPSLATE_BRICKS)
               .add(ModBlocks.MOSSY_DEEPSLATE_BRICKS_SLAB)
               .add(ModBlocks.MOSSY_DEEPSLATE_BRICKS_STAIRS)
               .add(ModBlocks.MOSSY_DEEPSLATE_BRICKS_WALL)

               .add(ModBlocks.MOSSY_DEEPSLATE_TILES)
               .add(ModBlocks.MOSSY_DEEPSLATE_TILES_SLAB)
               .add(ModBlocks.MOSSY_DEEPSLATE_TILES_STAIRS)
               .add(ModBlocks.MOSSY_DEEPSLATE_TILES_WALL)

               .add(ModBlocks.MOSSY_POLISHED_DEEPSLATE)
               .add(ModBlocks.MOSSY_POLISHED_DEEPSLATE_SLAB)
               .add(ModBlocks.MOSSY_POLISHED_DEEPSLATE_STAIRS)
               .add(ModBlocks.MOSSY_POLISHED_DEEPSLATE_WALL)

               .add(ModBlocks.CRACKED_POLISHED_DEEPSLATE)
               .add(ModBlocks.CRACKED_POLISHED_DEEPSLATE_SLAB)
               .add(ModBlocks.CRACKED_POLISHED_DEEPSLATE_STAIRS)
               .add(ModBlocks.CRACKED_POLISHED_DEEPSLATE_WALL)

               .add(ModBlocks.CHISELED_POLISHED_DEEPSLATE)
               .add(ModBlocks.CHISELED_DEEPSLATE_BRICKS)
               .add(ModBlocks.CHISELED_DEEPSLATE_TILES)
               .add(ModBlocks.CHISELED_SMOOTH_DEEPSLATE)

               .add(ModBlocks.DEEPSLATE_BRICKWORK)
               .add(ModBlocks.DEEPSLATE_BRICKWORK_SLAB)
               .add(ModBlocks.DEEPSLATE_BRICKWORK_STAIRS)
               .add(ModBlocks.DEEPSLATE_BRICKWORK_WALL)

               .add(ModBlocks.DEEPSLATE_PRESSURE_PLATE)
               .add(ModBlocks.DEEPSLATE_BUTTON)
               .add(ModBlocks.DEEPSLATE_TRAPDOOR)

               .add(ModBlocks.POLISHED_TUFF)
               .add(ModBlocks.TUFF_BRICKS)
               .add(ModBlocks.TUFF_BRICK_STAIRS)
               .add(ModBlocks.CHISELED_TUFF)
               .add(ModBlocks.TUFF_BRICK_SLAB)
               .add(ModBlocks.CHISELED_TUFF_BRICKS)
               .add(ModBlocks.POLISHED_TUFF_STAIRS)
               .add(ModBlocks.POLISHED_TUFF_SLAB)
               .add(ModBlocks.TUFF_SLAB)
               .add(ModBlocks.TUFF_STAIRS)
               .add(ModBlocks.TUFF_TRAPDOOR)
               .add(ModBlocks.COBBLED_BLUE_TUFF)
               .add(ModBlocks.COBBLED_BLUE_TUFF_SLAB)
               .add(ModBlocks.COBBLED_BLUE_TUFF_STAIRS)
               .add(ModBlocks.COBBLED_BLUE_TUFF_WALL)
               .add(ModBlocks.MOSSY_COBBLED_BLUE_TUFF)
               .add(ModBlocks.MOSSY_COBBLED_BLUE_TUFF_SLAB)
               .add(ModBlocks.MOSSY_COBBLED_BLUE_TUFF_STAIRS)
               .add(ModBlocks.MOSSY_COBBLED_BLUE_TUFF_WALL)
               .add(ModBlocks.BLUE_TUFF)
               .add(ModBlocks.BLUE_TUFF_SLAB)
               .add(ModBlocks.BLUE_TUFF_STAIRS)
               .add(ModBlocks.BLUE_TUFF_WALL)
               .add(ModBlocks.BLUE_TUFF_PILLAR)
               .add(ModBlocks.MOSSY_BLUE_TUFF_PILLAR)
               .add(ModBlocks.CRACKED_BLUE_TUFF_PILLAR)
               .add(ModBlocks.BLUE_TUFF_BRICKS)
               .add(ModBlocks.BLUE_TUFF_BRICKS_SLAB)
               .add(ModBlocks.BLUE_TUFF_BRICKS_STAIRS)
               .add(ModBlocks.BLUE_TUFF_BRICKS_WALL)
               .add(ModBlocks.MOSSY_BLUE_TUFF_BRICKS)
               .add(ModBlocks.MOSSY_BLUE_TUFF_BRICKS_SLAB)
               .add(ModBlocks.MOSSY_BLUE_TUFF_BRICKS_STAIRS)
               .add(ModBlocks.MOSSY_BLUE_TUFF_BRICKS_WALL)
               .add(ModBlocks.CRACKED_BLUE_TUFF_BRICKS)
               .add(ModBlocks.CRACKED_BLUE_TUFF_BRICKS_SLAB)
               .add(ModBlocks.CRACKED_BLUE_TUFF_BRICKS_STAIRS)
               .add(ModBlocks.CRACKED_BLUE_TUFF_BRICKS_WALL)
               .add(ModBlocks.BLUE_TUFF_TILES)
               .add(ModBlocks.BLUE_TUFF_TILES_SLAB)
               .add(ModBlocks.BLUE_TUFF_TILES_STAIRS)
               .add(ModBlocks.BLUE_TUFF_TILES_WALL)
               .add(ModBlocks.MOSSY_BLUE_TUFF_TILES)
               .add(ModBlocks.MOSSY_BLUE_TUFF_TILES_SLAB)
               .add(ModBlocks.MOSSY_BLUE_TUFF_TILES_STAIRS)
               .add(ModBlocks.MOSSY_BLUE_TUFF_TILES_WALL)
               .add(ModBlocks.CRACKED_BLUE_TUFF_TILES)
               .add(ModBlocks.CRACKED_BLUE_TUFF_TILES_SLAB)
               .add(ModBlocks.CRACKED_BLUE_TUFF_TILES_STAIRS)
               .add(ModBlocks.CRACKED_BLUE_TUFF_TILES_WALL)
               .add(ModBlocks.POLISHED_BLUE_TUFF)
               .add(ModBlocks.POLISHED_BLUE_TUFF_SLAB)
               .add(ModBlocks.POLISHED_BLUE_TUFF_STAIRS)
               .add(ModBlocks.POLISHED_BLUE_TUFF_WALL)
               .add(ModBlocks.MOSSY_POLISHED_BLUE_TUFF)
               .add(ModBlocks.MOSSY_POLISHED_BLUE_TUFF_SLAB)
               .add(ModBlocks.MOSSY_POLISHED_BLUE_TUFF_STAIRS)
               .add(ModBlocks.MOSSY_POLISHED_BLUE_TUFF_WALL)
               .add(ModBlocks.CRACKED_POLISHED_BLUE_TUFF)
               .add(ModBlocks.CRACKED_POLISHED_BLUE_TUFF_SLAB)
               .add(ModBlocks.CRACKED_POLISHED_BLUE_TUFF_STAIRS)
               .add(ModBlocks.CRACKED_POLISHED_BLUE_TUFF_WALL)
               .add(ModBlocks.CHISELED_POLISHED_BLUE_TUFF)
               .add(ModBlocks.CHISELED_BLUE_TUFF_BRICKS)
               .add(ModBlocks.BLUE_TUFF_PRESSURE_PLATE)
               .add(ModBlocks.BLUE_TUFF_BUTTON)
               .add(ModBlocks.BLUE_TUFF_TRAPDOOR)
               .add(ModBlocks.COBBLED_GREEN_TUFF)
               .add(ModBlocks.COBBLED_GREEN_TUFF_SLAB)
               .add(ModBlocks.COBBLED_GREEN_TUFF_STAIRS)
               .add(ModBlocks.COBBLED_GREEN_TUFF_WALL)
               .add(ModBlocks.SMOOTH_GREEN_TUFF)
               .add(ModBlocks.SMOOTH_GREEN_TUFF_SLAB)
               .add(ModBlocks.SMOOTH_GREEN_TUFF_STAIRS)
               .add(ModBlocks.SMOOTH_GREEN_TUFF_WALL)
               .add(ModBlocks.CRACKED_SMOOTH_GREEN_TUFF)
               .add(ModBlocks.CRACKED_SMOOTH_GREEN_TUFF_SLAB)
               .add(ModBlocks.CRACKED_SMOOTH_GREEN_TUFF_STAIRS)
               .add(ModBlocks.CRACKED_SMOOTH_GREEN_TUFF_WALL)
               .add(ModBlocks.MOSSY_COBBLED_GREEN_TUFF)
               .add(ModBlocks.MOSSY_COBBLED_GREEN_TUFF_SLAB)
               .add(ModBlocks.MOSSY_COBBLED_GREEN_TUFF_STAIRS)
               .add(ModBlocks.MOSSY_COBBLED_GREEN_TUFF_WALL)
               .add(ModBlocks.GREEN_TUFF)
               .add(ModBlocks.GREEN_TUFF_SLAB)
               .add(ModBlocks.GREEN_TUFF_STAIRS)
               .add(ModBlocks.GREEN_TUFF_WALL)
               .add(ModBlocks.GREEN_TUFF_PILLAR)
               .add(ModBlocks.MOSSY_GREEN_TUFF_PILLAR)
               .add(ModBlocks.CRACKED_GREEN_TUFF_PILLAR)
               .add(ModBlocks.GREEN_TUFF_BRICKS)
               .add(ModBlocks.GREEN_TUFF_BRICKS_SLAB)
               .add(ModBlocks.GREEN_TUFF_BRICKS_STAIRS)
               .add(ModBlocks.GREEN_TUFF_BRICKS_WALL)
               .add(ModBlocks.MOSSY_GREEN_TUFF_BRICKS)
               .add(ModBlocks.MOSSY_GREEN_TUFF_BRICKS_SLAB)
               .add(ModBlocks.MOSSY_GREEN_TUFF_BRICKS_STAIRS)
               .add(ModBlocks.MOSSY_GREEN_TUFF_BRICKS_WALL)
               .add(ModBlocks.CRACKED_GREEN_TUFF_BRICKS)
               .add(ModBlocks.CRACKED_GREEN_TUFF_BRICKS_SLAB)
               .add(ModBlocks.CRACKED_GREEN_TUFF_BRICKS_STAIRS)
               .add(ModBlocks.CRACKED_GREEN_TUFF_BRICKS_WALL)
               .add(ModBlocks.GREEN_TUFF_TILES)
               .add(ModBlocks.GREEN_TUFF_TILES_SLAB)
               .add(ModBlocks.GREEN_TUFF_TILES_STAIRS)
               .add(ModBlocks.GREEN_TUFF_TILES_WALL)
               .add(ModBlocks.MOSSY_GREEN_TUFF_TILES)
               .add(ModBlocks.MOSSY_GREEN_TUFF_TILES_SLAB)
               .add(ModBlocks.MOSSY_GREEN_TUFF_TILES_STAIRS)
               .add(ModBlocks.MOSSY_GREEN_TUFF_TILES_WALL)
               .add(ModBlocks.CRACKED_GREEN_TUFF_TILES)
               .add(ModBlocks.CRACKED_GREEN_TUFF_TILES_SLAB)
               .add(ModBlocks.CRACKED_GREEN_TUFF_TILES_STAIRS)
               .add(ModBlocks.CRACKED_GREEN_TUFF_TILES_WALL)
               .add(ModBlocks.POLISHED_GREEN_TUFF)
               .add(ModBlocks.POLISHED_GREEN_TUFF_SLAB)
               .add(ModBlocks.POLISHED_GREEN_TUFF_STAIRS)
               .add(ModBlocks.POLISHED_GREEN_TUFF_WALL)
               .add(ModBlocks.MOSSY_POLISHED_GREEN_TUFF)
               .add(ModBlocks.MOSSY_POLISHED_GREEN_TUFF_SLAB)
               .add(ModBlocks.MOSSY_POLISHED_GREEN_TUFF_STAIRS)
               .add(ModBlocks.MOSSY_POLISHED_GREEN_TUFF_WALL)
               .add(ModBlocks.CRACKED_POLISHED_GREEN_TUFF)
               .add(ModBlocks.CRACKED_POLISHED_GREEN_TUFF_SLAB)
               .add(ModBlocks.CRACKED_POLISHED_GREEN_TUFF_STAIRS)
               .add(ModBlocks.CRACKED_POLISHED_GREEN_TUFF_WALL)
               .add(ModBlocks.CHISELED_POLISHED_GREEN_TUFF)
               .add(ModBlocks.CHISELED_GREEN_TUFF)
               .add(ModBlocks.CHISELED_GREEN_TUFF_BRICKS)
               .add(ModBlocks.CHISELED_GREEN_TUFF_TILES)
               .add(ModBlocks.CHISELED_SMOOTH_GREEN_TUFF)
               .add(ModBlocks.GILDED_GREEN_TUFF)
               .add(ModBlocks.GILDED_GREEN_TUFF_SLAB)
               .add(ModBlocks.GILDED_GREEN_TUFF_STAIRS)
               .add(ModBlocks.GILDED_GREEN_TUFF_WALL)
               .add(ModBlocks.GILDED_CHISELED_POLISHED_GREEN_TUFF)
               .add(ModBlocks.GILDED_CHISELED_GREEN_TUFF)
               .add(ModBlocks.GILDED_CHISELED_GREEN_TUFF_BRICKS)
               .add(ModBlocks.GILDED_CHISELED_GREEN_TUFF_TILES)
               .add(ModBlocks.GILDED_CHISELED_SMOOTH_GREEN_TUFF)
               .add(ModBlocks.GREEN_TUFF_PRESSURE_PLATE)
               .add(ModBlocks.GREEN_TUFF_BUTTON)
               .add(ModBlocks.GREEN_TUFF_TRAPDOOR)
               .add(ModBlocks.GILDED_GREEN_TUFF_PRESSURE_PLATE)
               .add(ModBlocks.GILDED_GREEN_TUFF_BUTTON)
               .add(ModBlocks.GILDED_GREEN_TUFF_TRAPDOOR)
               .add(ModBlocks.OLD_TUFF)
               .add(ModBlocks.OLD_TUFF_SLAB)
               .add(ModBlocks.OLD_TUFF_STAIRS)
               .add(ModBlocks.OLD_TUFF_WALL)
               .add(ModBlocks.SMOOTH_TUFF)
               .add(ModBlocks.SMOOTH_TUFF_SLAB)
               .add(ModBlocks.SMOOTH_TUFF_STAIRS)
               .add(ModBlocks.SMOOTH_TUFF_WALL)
               .add(ModBlocks.MOSSY_SMOOTH_TUFF)
               .add(ModBlocks.MOSSY_SMOOTH_TUFF_SLAB)
               .add(ModBlocks.MOSSY_SMOOTH_TUFF_STAIRS)
               .add(ModBlocks.MOSSY_SMOOTH_TUFF_WALL)
               .add(ModBlocks.CRACKED_SMOOTH_TUFF)
               .add(ModBlocks.CRACKED_SMOOTH_TUFF_SLAB)
               .add(ModBlocks.CRACKED_SMOOTH_TUFF_STAIRS)
               .add(ModBlocks.CRACKED_SMOOTH_TUFF_WALL)
               .add(ModBlocks.COBBLED_TUFF)
               .add(ModBlocks.COBBLED_TUFF_SLAB)
               .add(ModBlocks.COBBLED_TUFF_STAIRS)
               .add(ModBlocks.COBBLED_TUFF_WALL)
               .add(ModBlocks.MOSSY_COBBLED_TUFF)
               .add(ModBlocks.MOSSY_COBBLED_TUFF_SLAB)
               .add(ModBlocks.MOSSY_COBBLED_TUFF_STAIRS)
               .add(ModBlocks.MOSSY_COBBLED_TUFF_WALL)
               .add(ModBlocks.TUFF_PILLAR)
               .add(ModBlocks.MOSSY_TUFF_PILLAR)
               .add(ModBlocks.CRACKED_TUFF_PILLAR)
               .add(ModBlocks.MOSSY_TUFF_BRICKS)
               .add(ModBlocks.MOSSY_TUFF_BRICKS_SLAB)
               .add(ModBlocks.MOSSY_TUFF_BRICKS_STAIRS)
               .add(ModBlocks.MOSSY_TUFF_BRICKS_WALL)
               .add(ModBlocks.CRACKED_TUFF_BRICKS)
               .add(ModBlocks.CRACKED_TUFF_BRICKS_SLAB)
               .add(ModBlocks.CRACKED_TUFF_BRICKS_STAIRS)
               .add(ModBlocks.CRACKED_TUFF_BRICKS_WALL)
               .add(ModBlocks.TUFF_TILES)
               .add(ModBlocks.TUFF_TILES_SLAB)
               .add(ModBlocks.TUFF_TILES_STAIRS)
               .add(ModBlocks.TUFF_TILES_WALL)
               .add(ModBlocks.MOSSY_TUFF_TILES)
               .add(ModBlocks.MOSSY_TUFF_TILES_SLAB)
               .add(ModBlocks.MOSSY_TUFF_TILES_STAIRS)
               .add(ModBlocks.MOSSY_TUFF_TILES_WALL)
               .add(ModBlocks.CRACKED_TUFF_TILES)
               .add(ModBlocks.CRACKED_TUFF_TILES_SLAB)
               .add(ModBlocks.CRACKED_TUFF_TILES_STAIRS)
               .add(ModBlocks.CRACKED_TUFF_TILES_WALL)
               .add(ModBlocks.MOSSY_POLISHED_TUFF)
               .add(ModBlocks.MOSSY_POLISHED_TUFF_SLAB)
               .add(ModBlocks.MOSSY_POLISHED_TUFF_STAIRS)
               .add(ModBlocks.MOSSY_POLISHED_TUFF_WALL)
               .add(ModBlocks.CRACKED_POLISHED_TUFF)
               .add(ModBlocks.CRACKED_POLISHED_TUFF_SLAB)
               .add(ModBlocks.CRACKED_POLISHED_TUFF_STAIRS)
               .add(ModBlocks.CRACKED_POLISHED_TUFF_WALL)
               .add(ModBlocks.CHISELED_POLISHED_TUFF)
               .add(ModBlocks.CHISELED_TUFF_TILES)
               .add(ModBlocks.CHISELED_SMOOTH_TUFF)
               .add(ModBlocks.TUFF_BRICKWORK)
               .add(ModBlocks.TUFF_BRICKWORK_SLAB)
               .add(ModBlocks.TUFF_BRICKWORK_STAIRS)
               .add(ModBlocks.TUFF_BRICKWORK_WALL)
               .add(ModBlocks.TUFF_CARVED_WINDOW_PANE)
               .add(ModBlocks.TUFF_CARVED_WINDOW);







        getOrCreateTagBuilder(BlockTags.NEEDS_STONE_TOOL)
                .add(Blocks.LAPIS_ORE)
                .add(Blocks.COPPER_ORE)
                .add(Blocks.DEEPSLATE_COPPER_ORE)
                .add(ModBlocks.TIN_BLOCK)
                .add(ModBlocks.RAW_TIN_BLOCK)
                .add(ModBlocks.TIN_ORE)
                .add(ModBlocks.DEEPSLATE_TIN_ORE)
                .add(ModBlocks.RAW_LEAD_BLOCK)
                .add(ModBlocks.LEAD_BLOCK)
                .add(ModBlocks.CUT_LEAD)
                .add(ModBlocks.DEEPSLATE_LEAD_ORE);

        getOrCreateTagBuilder(ModBlockTagProvider.NEEDS_BRONZE_TOOL)
                .add(Blocks.IRON_BLOCK)
                .add(Blocks.RAW_IRON_BLOCK)
                .add(Blocks.IRON_ORE)
                .add(Blocks.DEEPSLATE_IRON_ORE);


        getOrCreateTagBuilder(BlockTags.NEEDS_IRON_TOOL)
                .add(ModBlocks.RAW_SILVER_BLOCK)
                .add(ModBlocks.SILVER_BLOCK)
                .add(ModBlocks.DEEPSLATE_SILVER_ORE)
                .add(ModBlocks.KHAZAD_STEEL_BLOCK)
                .add(ModBlocks.BURZUM_STEEL_BLOCK)
                .add(ModBlocks.EDHEL_STEEL_BLOCK)
                .add(ModBlocks.CRUDE_BLOCK)
                .add(ModBlocks.CUT_LEAD);


        getOrCreateTagBuilder(BlockTags.NEEDS_DIAMOND_TOOL)
                .add(ModBlocks.RAW_MITHRIL_BLOCK)
                .add(ModBlocks.MITHRIL_BLOCK);

        getOrCreateTagBuilder(TagKey.of(RegistryKeys.BLOCK, new Identifier("fabric", "needs_tool_level_4")));


        getOrCreateTagBuilder(BlockTags.WALLS)
                .add(ModBlocks.STONE_BRICKWORK_WALL)
                .add(ModBlocks.STONE_TILES_WALL)
                .add(ModBlocks.CRACKED_SMOOTH_STONE_WALL)
                .add(ModBlocks.MOSSY_SMOOTH_STONE_WALL)
                .add(ModBlocks.POLISHED_STONE_WALL)
                .add(ModBlocks.MOSSY_POLISHED_STONE_WALL)
                .add(ModBlocks.CRACKED_POLISHED_STONE_WALL)
                .add(ModBlocks.MOSSY_STONE_TILES_WALL)
                .add(ModBlocks.CRACKED_STONE_TILES_WALL)
                .add(ModBlocks.OLD_STONE_WALL)
                .add(ModBlocks.SLATE_WALL)
                .add(ModBlocks.POLISHED_SLATE_WALL)
                .add(ModBlocks.SLATE_BRICKS_WALL)
                .add(ModBlocks.COBBLED_SLATE_WALL)
                .add(ModBlocks.OLD_DEEPSLATE_WALL)
                .add(ModBlocks.SMOOTH_DEEPSLATE_WALL)
                .add(ModBlocks.MOSSY_SMOOTH_DEEPSLATE_WALL)
                .add(ModBlocks.CRACKED_SMOOTH_DEEPSLATE_WALL)
                .add(ModBlocks.MOSSY_COBBLED_DEEPSLATE_WALL)
                .add(ModBlocks.MOSSY_DEEPSLATE_BRICKS_WALL)
                .add(ModBlocks.MOSSY_DEEPSLATE_TILES_WALL)
                .add(ModBlocks.CRACKED_POLISHED_DEEPSLATE_WALL)
                .add(ModBlocks.MOSSY_POLISHED_DEEPSLATE_WALL)
                .add(ModBlocks.DEEPSLATE_BRICKWORK_WALL)
                .add(ModBlocks.POLISHED_TUFF_WALL)
                .add(ModBlocks.TUFF_WALL)
                .add(ModBlocks.COBBLED_BLUE_TUFF_WALL)
                .add(ModBlocks.MOSSY_COBBLED_BLUE_TUFF_WALL)
                .add(ModBlocks.BLUE_TUFF_WALL)
                .add(ModBlocks.BLUE_TUFF_BRICKS_WALL)
                .add(ModBlocks.MOSSY_BLUE_TUFF_BRICKS_WALL)
                .add(ModBlocks.CRACKED_BLUE_TUFF_BRICKS_WALL)
                .add(ModBlocks.BLUE_TUFF_TILES_WALL)
                .add(ModBlocks.MOSSY_BLUE_TUFF_TILES_WALL)
                .add(ModBlocks.CRACKED_BLUE_TUFF_TILES_WALL)
                .add(ModBlocks.POLISHED_BLUE_TUFF_WALL)
                .add(ModBlocks.MOSSY_POLISHED_BLUE_TUFF_WALL)
                .add(ModBlocks.CRACKED_POLISHED_BLUE_TUFF_WALL)
                .add(ModBlocks.COBBLED_GREEN_TUFF_WALL)
                .add(ModBlocks.SMOOTH_GREEN_TUFF_WALL)
                .add(ModBlocks.CRACKED_SMOOTH_GREEN_TUFF_WALL)
                .add(ModBlocks.MOSSY_COBBLED_GREEN_TUFF_WALL)
                .add(ModBlocks.GREEN_TUFF_WALL)
                .add(ModBlocks.GREEN_TUFF_BRICKS_WALL)
                .add(ModBlocks.MOSSY_GREEN_TUFF_BRICKS_WALL)
                .add(ModBlocks.CRACKED_GREEN_TUFF_BRICKS_WALL)
                .add(ModBlocks.GREEN_TUFF_TILES_WALL)
                .add(ModBlocks.MOSSY_GREEN_TUFF_TILES_WALL)
                .add(ModBlocks.CRACKED_GREEN_TUFF_TILES_WALL)
                .add(ModBlocks.POLISHED_GREEN_TUFF_WALL)
                .add(ModBlocks.MOSSY_POLISHED_GREEN_TUFF_WALL)
                .add(ModBlocks.CRACKED_POLISHED_GREEN_TUFF_WALL)
                .add(ModBlocks.GILDED_GREEN_TUFF_WALL)
                .add(ModBlocks.OLD_TUFF_WALL)
                .add(ModBlocks.SMOOTH_TUFF_WALL)
                .add(ModBlocks.MOSSY_SMOOTH_TUFF_WALL)
                .add(ModBlocks.CRACKED_SMOOTH_TUFF_WALL)
                .add(ModBlocks.COBBLED_TUFF_WALL)
                .add(ModBlocks.MOSSY_COBBLED_TUFF_WALL)
                .add(ModBlocks.MOSSY_TUFF_BRICKS_WALL)
                .add(ModBlocks.CRACKED_TUFF_BRICKS_WALL)
                .add(ModBlocks.TUFF_TILES_WALL)
                .add(ModBlocks.MOSSY_TUFF_TILES_WALL)
                .add(ModBlocks.CRACKED_TUFF_TILES_WALL)
                .add(ModBlocks.MOSSY_POLISHED_TUFF_WALL)
                .add(ModBlocks.CRACKED_POLISHED_TUFF_WALL)
                .add(ModBlocks.TUFF_BRICKWORK_WALL)
                .add(ModBlocks.TUFF_BRICK_WALL);


        getOrCreateTagBuilder(ModTags.MINEABLE_WITH_KNIFE)
                .add(Blocks.CAKE);

        getOrCreateTagBuilder(ModTags.DROPS_CAKE_SLICE);

        getOrCreateTagBuilder(ModTags.MINEABLE_WITH_KNIFE)
                .add(Blocks.COBWEB)
                .forceAddTag(BlockTags.LEAVES)
                .add(Blocks.VINE)
                .add(Blocks.GLOW_LICHEN)
                .add(Blocks.TALL_GRASS)
                .add(Blocks.GRASS)
                .add(Blocks.FERN)
                .add(Blocks.LARGE_FERN)
                .add(Blocks.DEAD_BUSH)
                .add(Blocks.HANGING_ROOTS)
                .add(Blocks.NETHER_SPROUTS)
                .add(Blocks.WARPED_ROOTS)
                .add(Blocks.CRIMSON_ROOTS)
                .add(Blocks.TWISTING_VINES)
                .add(Blocks.WEEPING_VINES)
                .add(Blocks.CAVE_VINES);

        getOrCreateTagBuilder(BlockTags.CLIMBABLE)
                .add(ModBlocks.ROPE);

    }
}
